name: Danger CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Danger
    steps:
      - uses: actions/checkout@v3
      - name: Danger
        ## uses: danger/kotlin@1.1.0
        uses: docker://ghcr.io/danger/danger-swift-with-swiftlint:3.12.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
